// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj0PsjqOyjp0UhSRoitiJf9xdvT1ELRjQ',
    appId: '1:871935467774:web:f59a22b0960a7da11845af',
    messagingSenderId: '871935467774',
    projectId: 'invoice-maker-d3602',
    authDomain: 'invoice-maker-d3602.firebaseapp.com',
    storageBucket: 'invoice-maker-d3602.appspot.com',
    measurementId: 'G-L16N8TZM53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAbyNf6n7ihyDgO1tgWapt7_WB6tit71w',
    appId: '1:871935467774:android:4318e59ff829ff2d1845af',
    messagingSenderId: '871935467774',
    projectId: 'invoice-maker-d3602',
    storageBucket: 'invoice-maker-d3602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXz0LBZo2UlAoKiscs8cfKRnOqtbWVVDI',
    appId: '1:871935467774:ios:7782d2e171f400511845af',
    messagingSenderId: '871935467774',
    projectId: 'invoice-maker-d3602',
    storageBucket: 'invoice-maker-d3602.appspot.com',
    iosBundleId: 'com.example.invoiceMaker',
  );
}
